version: '3'
services:
  server-proxy:
    image: fletamar/mini_server:server
    container_name: server
    networks:
      - server_network
    ports:
      - "80:81"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:81 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

  nginx-proxy:
    image: nginx:latest
    container_name: nginx_server
    networks:
      - server_network
    ports:
      - "8080:80"
    depends_on:
      - server-proxy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  server_network:
